### ISSUE TITLE
Email 报警失效

### ISSUE THREAD

**Issue by amio** [amio/eb#60]
有个报错 

```
eb-1 (err): /srv/www/eb/node_modules/lodash/index.js:10207
eb-1 (err):         throw result;
eb-1 (err):               ^
eb-1 (err): SyntaxError: Unexpected token >
eb-1 (err):     at Function (native)
eb-1 (err):     at /srv/www/eb/node_modules/lodash/index.js:10200:16
eb-1 (err):     at attempt (/srv/www/eb/node_modules/lodash/index.js:10480:21)
eb-1 (err):     at Function.template (/srv/www/eb/node_modules/lodash/index.js:10199:20)
eb-1 (err):     at /srv/www/eb/server/error-alert.js:47:26
eb-1 (err):     at callback (/srv/www/eb/node_modules/nedb/lib/executor.js:30:17)
eb-1 (err):     at Cursor.execFn (/srv/www/eb/node_modules/nedb/lib/datastore.js:424:12)
eb-1 (err):     at Cursor._exec (/srv/www/eb/node_modules/nedb/lib/cursor.js:172:17)
eb-1 (err):     at /srv/www/eb/node_modules/nedb/lib/executor.js:40:13
eb-1 (err):     at Immediate.q.process [as _onImmediate] (/srv/www/eb/node_modules/nedb/node_modules/async/lib/async.js:731:21)
```

**Comment by codinfox** [comment]
两个原因：
1. 之前的模板的格式错了，解析不了
2. postfix这个服务需要手动启动，之前貌似服务器重启过？重启之后没有启动postfix，所以邮件都积压在本机，没法出去。

**Comment by amio** [comment]
查内存问题的时候忘记什么原因重启了下
